// File generated by the FlutterFire CLI — placeholder version.
//
// This file ships with dummy project values so the app builds out of the
// box. Before running against a real Firebase backend, replace this file by
// running (from the project root):
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// See README.md for the full setup walkthrough.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate platform options.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'financial-padi',
    authDomain: 'financial-padi.firebaseapp.com',
    storageBucket: 'financial-padi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'financial-padi',
    storageBucket: 'financial-padi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'financial-padi',
    storageBucket: 'financial-padi.appspot.com',
    iosBundleId: 'com.financialpadi.financialPadi',
  );
}
